### ISSUE TITLE
"Installation and updates are x% complete" spam

### ISSUE THREAD

**Issue by L0Lock** [pop-os/cosmic-store#107] opened 2024-07-02 14:32 UTC
![image](https://github.com/pop-os/cosmic-store/assets/16049822/64a18b4a-f0af-4fde-9465-04094737ffe5)

![image](https://github.com/pop-os/cosmic-store/assets/16049822/aee7e2e4-b050-4c3b-a16e-7e3ca10d2f3d)

[Screencast from 07-02-2024 10:05:32 AM.webm](https://github.com/pop-os/cosmic-store/assets/16049822/f7fb91cb-6e42-4900-8e77-7be409c313e4)

This notification keeps appearing and disappearing both in the screen corner and the notifications list.

It seems to occur  especially when the Cosmic Store window is closed while still doing things in the background.

Pop!_OS 22.04 LTS

**Comment by leviport** [comment] 2024-07-02 14:36
Duplicate of https://github.com/pop-os/cosmic-store/issues/84

Please report your `apt policy cosmic-store` in that issue. If the bug is still present after the commit that was tagged as closing it, we can reopen that issue.

**Closed by leviport** 2024-07-02 14:36 UTC
